const CONFIG = window.SURVEY_CONFIG;
const COPY = {
  en:{aboutTitle:"A little about you",aboutDescription:"Choose your preferred language and share a few basic details.",sectionOne:"Section one",language:"Survey language",age:"Age group",identity:"What is your gender identity?",occupation:"Current occupation",select:"Select",aboutYou:"About you",question:"Question",back:"Back",continue:"Continue",submit:"Submit",submitting:"Submitting...",anonymous:"Your response remains anonymous.",completeAbout:"Please complete all fields.",selectOption:"Please select an option.",selectOne:"Please select at least one option.",thankEyebrow:"Response submitted",thankTitle:"Thank you for sharing your experience.",thankMessage:"Your response has been recorded anonymously.",comingSoon:"Coming soon",comingSoonText:"A thoughtful experience, right at your fingertips.",errorEyebrow:"Submission interrupted",errorTitle:"We could not save your response.",errorMessage:"Please check your connection and try again.",retry:"Try again"},
  hi:{aboutTitle:"आपके बारे में थोड़ा सा",aboutDescription:"अपनी पसंदीदा भाषा चुनें और कुछ सामान्य जानकारी साझा करें।",sectionOne:"प्रथम भाग",language:"सर्वे की भाषा",age:"आयु वर्ग",identity:"आप अपनी लैंगिक पहचान कैसे बताते हैं?",occupation:"वर्तमान व्यवसाय",select:"चुनें",aboutYou:"आपके बारे में",question:"प्रश्न",back:"पीछे",continue:"आगे",submit:"जमा करें",submitting:"जमा हो रहा है...",anonymous:"आपकी प्रतिक्रिया गुमनाम रहेगी।",completeAbout:"कृपया सभी जानकारी भरें।",selectOption:"कृपया एक विकल्प चुनें।",selectOne:"कृपया कम से कम एक विकल्प चुनें।",thankEyebrow:"प्रतिक्रिया जमा हो गई",thankTitle:"अपना अनुभव साझा करने के लिए धन्यवाद।",thankMessage:"आपकी प्रतिक्रिया गुमनाम रूप से दर्ज कर ली गई है।",comingSoon:"जल्द आ रहा है",comingSoonText:"एक बेहतर अनुभव, अब आपकी उंगलियों पर।",errorEyebrow:"जमा करने में समस्या",errorTitle:"आपकी प्रतिक्रिया सुरक्षित नहीं हो सकी।",errorMessage:"कृपया इंटरनेट कनेक्शन जांचें और दोबारा प्रयास करें।",retry:"फिर प्रयास करें"}
};
const ABOUT = {
 age:{en:["Under 18","18–24","25–34","35–44","45–54","55 or above","Prefer not to say"],hi:["18 वर्ष से कम","18–24","25–34","35–44","45–54","55 वर्ष या अधिक","बताना नहीं चाहते"]},
 identity:{en:["Female","Male","Other"],hi:["महिला","पुरुष","अन्य"]},
 occupation:{en:["Student","Salaried professional","Business owner or self-employed","Homemaker","Freelancer","Other","Prefer not to say"],hi:["विद्यार्थी","वेतनभोगी पेशेवर","व्यवसायी या स्वरोज़गार","गृहिणी / गृहस्थ","फ्रीलांसर","अन्य","बताना नहीं चाहते"]}
};
const QUESTIONS = [
 {en:'How often do you feel, “I have nothing to wear”?',hi:'आपको कितनी बार लगता है, “मेरे पास पहनने के लिए कुछ नहीं है”?',enO:["Rarely","Sometimes","Often","Almost every day"],hiO:["कभी-कभार","कभी-कभी","अक्सर","लगभग हर दिन"]},
 {en:"How often do you feel that you want to improve your style when going out?",hi:"बाहर जाते समय आपको कितनी बार लगता है कि आप अपनी स्टाइल बेहतर करना चाहते हैं?",enO:["Rarely","Sometimes","Often","Almost every day"],hiO:["कभी-कभार","कभी-कभी","अक्सर","लगभग हर दिन"]},
 {en:"Do you ever feel that your wardrobe is missing something, but you cannot identify what it is?",hi:"क्या आपको कभी लगता है कि आपकी अलमारी में कुछ कमी है, लेकिन आप समझ नहीं पाते कि क्या?",enO:["Rarely","Sometimes","Often","Almost every day"],hiO:["कभी-कभार","कभी-कभी","अक्सर","लगभग हर दिन"]},
 {en:"How often do you plan outfits in advance for specific occasions or events?",hi:"विशेष अवसरों या कार्यक्रमों के लिए आप कितनी बार पहले से कपड़े तय करते हैं?",enO:["Never","Sometimes","Often","Always"],hiO:["कभी नहीं","कभी-कभी","अक्सर","हमेशा"]},
 {en:"Do you have clothes in your wardrobe that you have never worn or rarely wear?",hi:"क्या आपकी अलमारी में ऐसे कपड़े हैं जिन्हें आपने कभी नहीं पहना या बहुत कम पहनते हैं?",enO:["Yes, many","Yes, a few","Very few","No"],hiO:["हाँ, बहुत सारे","हाँ, कुछ","बहुत कम","नहीं"]},
 {en:"How many clothes in your wardrobe no longer suit your style?",hi:"आपकी अलमारी में कितने कपड़े अब आपकी स्टाइल के अनुसार नहीं हैं?",enO:["Many","Some","Very few","None"],hiO:["बहुत सारे","कुछ","बहुत कम","एक भी नहीं"]},
 {en:"How interested are you in having more outfit options while keeping fewer clothes in your wardrobe?",hi:"कम कपड़ों के साथ अधिक पहनने योग्य आउटफिट विकल्प रखने में आपकी कितनी रुचि है?",enO:["Not interested","Slightly interested","Interested","Very interested"],hiO:["रुचि नहीं है","थोड़ी रुचि है","रुचि है","बहुत रुचि है"]},
 {en:"How often do you need help deciding what clothing item to buy next?",hi:"अगली बार कौन-सा कपड़ा खरीदना चाहिए, यह तय करने में आपको कितनी बार मदद की आवश्यकता होती है?",enO:["Rarely","Sometimes","Often","Very often"],hiO:["कभी-कभार","कभी-कभी","अक्सर","बहुत अक्सर"]},
 {en:"How often do you shop for clothes?",hi:"आप कपड़ों की खरीदारी कितनी बार करते हैं?",enO:["Weekly","Monthly","Once every 2–3 months","A few times a year","Only when required"],hiO:["हर सप्ताह","हर महीने","हर 2–3 महीने में एक बार","साल में कुछ बार","केवल आवश्यकता होने पर"]},
 {en:"Where do you usually shop for clothes?",hi:"आप सामान्यतः कपड़ों की खरीदारी कहाँ से करते हैं?",type:"checkbox",enO:["Local stores (Offline)","Myntra","AJIO","Nykaa Fashion","Tata CLiQ","Other"],hiO:["स्थानीय दुकानें (ऑफलाइन)","Myntra","AJIO","Nykaa Fashion","Tata CLiQ","अन्य"]},
 {en:"How often do you need someone’s opinion while choosing what to wear from your existing wardrobe?",hi:"अपनी मौजूदा अलमारी से क्या पहनना है, यह चुनते समय आपको कितनी बार किसी की राय की आवश्यकता होती है?",enO:["Rarely","Sometimes","Often","Very often"],hiO:["कभी-कभार","कभी-कभी","अक्सर","बहुत अक्सर"]}
];
const state={currentStep:0,language:"en",answers:{}};
const $=id=>document.getElementById(id);
const els={closedView:$("closedView"),introView:$("introView"),surveyView:$("surveyView"),thankYouView:$("thankYouView"),errorView:$("errorView"),closedTitle:$("closedTitle"),closedMessage:$("closedMessage"),introVideo:$("introVideo"),videoPlaceholder:$("videoPlaceholder"),videoStatus:$("videoStatus"),continueWithoutVideo:$("continueWithoutVideo"),videoProgress:$("videoProgress"),skipIntro:$("skipIntro"),stepContainer:$("stepContainer"),stepLabel:$("stepLabel"),progressCount:$("progressCount"),progressPercent:$("progressPercent"),surveyProgress:$("surveyProgress"),backButton:$("backButton"),nextButton:$("nextButton"),anonymousNote:$("anonymousNote"),retryButton:$("retryButton")};
function showView(v){[els.closedView,els.introView,els.surveyView,els.thankYouView,els.errorView].forEach(x=>x.classList.add("hidden"));v.classList.remove("hidden")}
function availability(){const n=new Date();if(!CONFIG.surveyOpen)return{open:false,title:CONFIG.closedTitle,message:CONFIG.closedMessage};if(CONFIG.openingDate&&n<new Date(CONFIG.openingDate))return{open:false,title:CONFIG.notStartedTitle,message:CONFIG.notStartedMessage};if(CONFIG.closingDate&&n>new Date(CONFIG.closingDate))return{open:false,title:CONFIG.endedTitle,message:CONFIG.endedMessage};return{open:true}}
function startApp(){const a=availability();if(!a.open){els.closedTitle.textContent=a.title;els.closedMessage.textContent=a.message;showView(els.closedView);return}showView(els.introView);startIntro()}
function startIntro(){const started=Date.now(),duration=Math.max(1000,CONFIG.introDurationSeconds*1000);let done=false,ready=false;const go=()=>{if(done)return;done=true;try{els.introVideo.pause()}catch{}showView(els.surveyView);applyLanguage();renderStep()};const fallback=()=>{if(ready||done)return;els.videoStatus.textContent="Video could not be loaded. You can continue with the survey.";els.continueWithoutVideo.classList.remove("hidden")};els.skipIntro.onclick=go;els.continueWithoutVideo.onclick=go;els.introVideo.onended=go;const readyFn=()=>{if(ready)return;ready=true;els.videoPlaceholder.classList.add("hidden");els.introVideo.play().catch(fallback)};els.introVideo.addEventListener("loadeddata",readyFn,{once:true});els.introVideo.addEventListener("canplay",readyFn,{once:true});els.introVideo.addEventListener("error",fallback,{once:true});els.introVideo.addEventListener("stalled",fallback);setTimeout(fallback,3000);const timer=setInterval(()=>{if(done){clearInterval(timer);return}const elapsed=Date.now()-started;const useVideo=Number.isFinite(els.introVideo.duration)&&els.introVideo.duration>0&&els.introVideo.currentTime>0;const p=useVideo?Math.min(100,els.introVideo.currentTime/els.introVideo.duration*100):Math.min(100,elapsed/duration*100);els.videoProgress.style.width=`${p}%`;if(elapsed>=duration+500)go()},100)}
function applyLanguage(){const c=COPY[state.language];document.documentElement.lang=state.language;els.backButton.textContent=c.back;els.anonymousNote.textContent=c.anonymous}
function renderStep(){const c=COPY[state.language],total=QUESTIONS.length+1,num=state.currentStep+1,p=Math.round(num/total*100);els.stepLabel.textContent=state.currentStep===0?c.aboutYou:`${c.question} ${state.currentStep}`;els.progressCount.textContent=`${num} / ${total}`;els.progressPercent.textContent=`${p}%`;els.surveyProgress.style.width=`${p}%`;els.backButton.disabled=state.currentStep===0;els.nextButton.textContent=state.currentStep===QUESTIONS.length?c.submit:c.continue;els.anonymousNote.textContent=c.anonymous;state.currentStep===0?renderAbout():renderQuestion(QUESTIONS[state.currentStep-1])}
function options(list,selected){return `<option value="">${COPY[state.language].select}</option>`+list.map(x=>`<option value="${esc(x)}" ${selected===x?"selected":""}>${esc(x)}</option>`).join("")}
function renderAbout(){const c=COPY[state.language];els.stepContainer.innerHTML=`<div class="step-card"><p class="eyebrow">${c.sectionOne}</p><h2>${c.aboutTitle}</h2><p class="step-description">${c.aboutDescription}</p><div class="field"><label>${c.language}</label><div class="language-choice"><label class="language-card"><input type="radio" name="language" value="en" ${state.language==="en"?"checked":""}><span>English</span></label><label class="language-card"><input type="radio" name="language" value="hi" ${state.language==="hi"?"checked":""}><span>हिन्दी</span></label></div></div><div class="about-grid"><div class="field"><label for="age">${c.age}</label><select id="age">${options(ABOUT.age[state.language],state.answers.age)}</select></div><div class="field"><label for="identity">${c.identity}</label><select id="identity">${options(ABOUT.identity[state.language],state.answers.identity)}</select></div><div class="field full"><label for="occupation">${c.occupation}</label><select id="occupation">${options(ABOUT.occupation[state.language],state.answers.occupation)}</select></div></div></div>`;document.querySelectorAll('input[name="language"]').forEach(i=>i.onchange=e=>{state.language=e.target.value;state.answers.age=state.answers.identity=state.answers.occupation="";applyLanguage();renderStep()})}
function renderQuestion(q){const key=`q${state.currentStep}`,saved=state.answers[key]||(q.type==="checkbox"?[]:""),type=q.type||"radio",title=q[state.language],opts=q[state.language==="hi"?"hiO":"enO"],c=COPY[state.language];els.stepContainer.innerHTML=`<div class="step-card"><p class="eyebrow">${c.question} ${state.currentStep}</p><h2>${esc(title)}</h2><div class="options">${opts.map(o=>{const checked=type==="checkbox"?saved.includes(o):saved===o;return `<label class="option"><input type="${type}" name="${key}" value="${esc(o)}" ${checked?"checked":""}><span>${esc(o)}</span></label>`}).join("")}</div></div>`}
function save(){const c=COPY[state.language];if(state.currentStep===0){const l=document.querySelector('input[name="language"]:checked'),a=$("age").value,i=$("identity").value,o=$("occupation").value;if(!l||!a||!i||!o){alert(c.completeAbout);return false}state.language=l.value;state.answers.age=a;state.answers.identity=i;state.answers.occupation=o;return true}const q=QUESTIONS[state.currentStep-1],key=`q${state.currentStep}`;if(q.type==="checkbox"){const v=[...document.querySelectorAll(`input[name="${key}"]:checked`)].map(x=>x.value);if(!v.length){alert(c.selectOne);return false}state.answers[key]=v}else{const v=document.querySelector(`input[name="${key}"]:checked`);if(!v){alert(c.selectOption);return false}state.answers[key]=v.value}return true}
function next(){if(!save())return;if(state.currentStep<QUESTIONS.length){state.currentStep++;renderStep();scrollTo({top:0,behavior:"smooth"})}else submitSurvey()}
function back(){if(state.currentStep>0){state.currentStep--;renderStep();scrollTo({top:0,behavior:"smooth"})}}
function payload(){return{submittedAt:new Date().toISOString(),surveyVersion:"2.0-bilingual",language:state.language==="hi"?"Hindi":"English",age:state.answers.age,identity:state.answers.identity,occupation:state.answers.occupation,responses:[{questionNumber:0,question:"Survey language",answer:state.language==="hi"?"Hindi":"English"},...QUESTIONS.map((q,i)=>({questionNumber:i+1,question:q.en,displayedQuestion:q[state.language],answer:state.answers[`q${i+1}`]}))]}}
async function submitSurvey(){const c=COPY[state.language];els.nextButton.disabled=true;els.nextButton.textContent=c.submitting;try{const body=payload();if(!CONFIG.apiUrl||CONFIG.apiUrl.includes("PASTE_YOUR")){localStorage.setItem("wardrobeSurveyDemoResponse",JSON.stringify(body));showThank();return}const r=await fetch(CONFIG.apiUrl,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)});if(!r.ok)throw Error();const j=await r.json();if(!j.success)throw Error();showThank()}catch(e){showError()}finally{els.nextButton.disabled=false;els.nextButton.textContent=c.submit}}
function showThank(){const c=COPY[state.language];$("thankEyebrow").textContent=c.thankEyebrow;$("thankTitle").textContent=c.thankTitle;$("thankMessage").textContent=c.thankMessage;$("comingSoonLabel").textContent=c.comingSoon;$("comingSoonText").textContent=c.comingSoonText;showView(els.thankYouView)}
function showError(){const c=COPY[state.language];$("errorEyebrow").textContent=c.errorEyebrow;$("errorTitle").textContent=c.errorTitle;$("errorMessage").textContent=c.errorMessage;els.retryButton.textContent=c.retry;showView(els.errorView)}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
els.nextButton.onclick=next;els.backButton.onclick=back;els.retryButton.onclick=()=>{showView(els.surveyView);submitSurvey()};startApp();
